storage-infra_hosts:
  {{ inventory_hostname }}:
    container_vars:
      cinder_qos_specs:
        - cinder_volume_types:
            - low-iops
          name: low-iops
          options:
            consumer: front-end
            read_iops_sec: 75
            write_iops_sec: 75
        - cinder_volume_types:
            - high-iops
          name: high-iops
          options:
            consumer: front-end
            read_iops_sec: 150
            write_iops_sec: 150
        - cinder_volume_types:
            - ultra-high-iops
          name: ultra-high-iops
          options:
            consumer: front-end
            read_iops_sec: 300
            write_iops_sec: 300
    ip: 172.29.236.100
storage_hosts:
  {{ inventory_hostname }}:
    ip: 172.29.236.100