network-gateway_hosts:
  {{ inventory_hostname }}:
    ip: 172.29.236.100
network-northd_hosts:
  {{ inventory_hostname }}:
    ip: 172.29.236.100
network_hosts:
  {{ inventory_hostname }}:
    ip: 172.29.236.100