# Define CIDRs for networks
cidr_networks:
  management: 172.29.236.0/22
  storage: 172.29.244.0/22
  tunnel: 172.29.240.0/22

global_overrides:
  # Set load balancer IPs
  external_lb_vip_address: {{ host_ip }}
  internal_lb_vip_address: 172.29.236.101

  management_bridge: br-mgmt

  # Use containers or not
  no_containers: false

  # Define provider networks to use in Neutron
  provider_networks:
    - network:
        container_bridge: br-mgmt
        container_interface: eth1
        container_type: veth
        group_binds:
          - all_containers
          - hosts
        ip_from_q: management
        is_management_address: true
        static_routes:
          - cidr: {{ host_cidr }}
            gateway: 172.29.236.100
        type: raw
    - network:
        container_bridge: br-vxlan
        container_interface: eth10
        container_type: veth
        group_binds:
          - neutron_ovn_controller
        ip_from_q: tunnel
        net_name: geneve
        range: 1:1000
        type: geneve
    - network:
        container_bridge: br-provider
        group_binds:
          - neutron_ovn_gateway
        net_name: physnet1
        network_interface: eth12
        range: 101:200,301:400
        type: vlan
    - network:
        container_bridge: br-provider
        container_type: veth
        group_binds:
          - neutron_ovn_gateway
        net_name: physnet1
        type: flat
    - network:
        container_bridge: br-storage
        container_interface: eth2
        container_type: veth
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute
          - manila_share
          - swift_proxy
          - ceph-mon
          - ceph-osd
        ip_from_q: storage
        type: raw

identity_hosts:
  {{ inventory_hostname }}:
    ip: 172.29.236.100

repo-infra_hosts:
  {{ inventory_hostname }}:
    ip: 172.29.236.100

shared-infra_hosts:
  {{ inventory_hostname }}:
    ip: 172.29.236.100

# Tell OSA what IPs are off limits.
used_ips:
  - 172.29.236.1,172.29.236.50
  - 172.29.236.100
  - 172.29.236.101
  - 172.29.240.1,172.29.240.50
  - 172.29.240.100
  - 172.29.244.1,172.29.244.50
  - 172.29.244.100
  - 172.29.248.1,172.29.248.50
  - 172.29.248.100